name: Unit tests #does not matter. String; can have spaces. If you have multiple workflows, good to use a useful name

on: # what events trigger our workflow
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs: # useful names are important
  code_style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pycodestyle $(git ls-files "*.py") # nice way of generalizing and not having to list every python file
      
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd test/unit
          python -m unittest test_utils
